import DonationSection from "@/components/DonationSection";
import DownloadSection from "@/components/DownloadSection";
import Navbar from "@/components/Navbar";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chess App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex
        alignItems="center"
        margin="0 auto"
        h={{ base: "calc(100vh - 114px)", md: "calc(100vh - 120px)" }}
      >
        <DownloadSection />
      </Flex>
      <DonationSection />
    </>
  );
}
